package no.met.metdata.proxy;


/**
 * Java Bean: no_met_metdata_TimeSerieTypes
 *    for Web service proxy: MetDataServiceProxy
 *    generated by Oracle WSDL toolkit (Version: 1.0).
 */
public class no_met_metdata_TimeSerieTypes {

    public no_met_metdata_TimeSerieTypes() {

    }

    public no_met_metdata_TimeSerieTypes(java.lang.String _language, java.lang.String _table, java.lang.String _elemTable, java.lang.String _serieTypeName, java.lang.Integer _serieTypeID, java.lang.String _serieTypeDescription) {
        m_language = _language;
        m_table = _table;
        m_elemTable = _elemTable;
        m_serieTypeName = _serieTypeName;
        m_serieTypeID = _serieTypeID;
        m_serieTypeDescription = _serieTypeDescription;

    }

    public java.lang.String getLanguage() {
        return m_language;

    }

    public void setLanguage(java.lang.String _language) {
        m_language = _language;

    }

    public java.lang.String getTable() {
        return m_table;

    }

    public void setTable(java.lang.String _table) {
        m_table = _table;

    }

    public java.lang.String getElemTable() {
        return m_elemTable;

    }

    public void setElemTable(java.lang.String _elemTable) {
        m_elemTable = _elemTable;

    }

    public java.lang.String getSerieTypeName() {
        return m_serieTypeName;

    }

    public void setSerieTypeName(java.lang.String _serieTypeName) {
        m_serieTypeName = _serieTypeName;

    }

    public java.lang.Integer getSerieTypeID() {
        return m_serieTypeID;

    }

    public void setSerieTypeID(java.lang.Integer _serieTypeID) {
        m_serieTypeID = _serieTypeID;

    }

    public java.lang.String getSerieTypeDescription() {
        return m_serieTypeDescription;

    }

    public void setSerieTypeDescription(java.lang.String _serieTypeDescription) {
        m_serieTypeDescription = _serieTypeDescription;

    }


    private java.lang.String m_language;
    private java.lang.String m_table;
    private java.lang.String m_elemTable;
    private java.lang.String m_serieTypeName;
    private java.lang.Integer m_serieTypeID;
    private java.lang.String m_serieTypeDescription;

}
