package no.met.metdata.proxy;


/**
 * Java Bean: no_met_metdata_ElementProperties
 *    for Web service proxy: MetDataServiceProxy
 *    generated by Oracle WSDL toolkit (Version: 1.0).
 */
public class no_met_metdata_ElementProperties {

    public no_met_metdata_ElementProperties() {

    }

    public no_met_metdata_ElementProperties(java.lang.String _elemCode, java.lang.Integer _elemNo, java.lang.String _description, java.lang.String _unit, java.lang.String _name, java.lang.String _elemGroup, java.lang.String _language, java.util.Date _fromdate, java.util.Date _todate) {
        m_elemCode = _elemCode;
        m_elemNo = _elemNo;
        m_description = _description;
        m_unit = _unit;
        m_name = _name;
        m_elemGroup = _elemGroup;
        m_language = _language;
        m_fromdate = _fromdate;
        m_todate = _todate;

    }

    public java.lang.String getElemCode() {
        return m_elemCode;

    }

    public void setElemCode(java.lang.String _elemCode) {
        m_elemCode = _elemCode;

    }

    public java.lang.Integer getElemNo() {
        return m_elemNo;

    }

    public void setElemNo(java.lang.Integer _elemNo) {
        m_elemNo = _elemNo;

    }

    public java.lang.String getDescription() {
        return m_description;

    }

    public void setDescription(java.lang.String _description) {
        m_description = _description;

    }

    public java.lang.String getUnit() {
        return m_unit;

    }

    public void setUnit(java.lang.String _unit) {
        m_unit = _unit;

    }

    public java.lang.String getName() {
        return m_name;

    }

    public void setName(java.lang.String _name) {
        m_name = _name;

    }

    public java.lang.String getElemGroup() {
        return m_elemGroup;

    }

    public void setElemGroup(java.lang.String _elemGroup) {
        m_elemGroup = _elemGroup;

    }

    public java.lang.String getLanguage() {
        return m_language;

    }

    public void setLanguage(java.lang.String _language) {
        m_language = _language;

    }

    public java.util.Date getFromdate() {
        return m_fromdate;

    }

    public void setFromdate(java.util.Date _fromdate) {
        m_fromdate = _fromdate;

    }

    public java.util.Date getTodate() {
        return m_todate;

    }

    public void setTodate(java.util.Date _todate) {
        m_todate = _todate;

    }


    private java.lang.String m_elemCode;
    private java.lang.Integer m_elemNo;
    private java.lang.String m_description;
    private java.lang.String m_unit;
    private java.lang.String m_name;
    private java.lang.String m_elemGroup;
    private java.lang.String m_language;
    private java.util.Date m_fromdate;
    private java.util.Date m_todate;

}
