package no.met.metdata.proxy;


/**
 * Java Bean: no_met_metdata_StationProperties
 *    for Web service proxy: MetDataServiceProxy
 *    generated by Oracle WSDL toolkit (Version: 1.0).
 */
public class no_met_metdata_StationProperties {

    public no_met_metdata_StationProperties() {

    }

    public no_met_metdata_StationProperties(java.lang.String _name, java.lang.Integer _stnr, java.lang.Integer _wmoNo, java.lang.Integer _amsl, java.lang.String _department, java.lang.Integer _municipalityNo, java.lang.Integer _fromYear, java.lang.Integer _fromMonth, java.lang.Integer _fromDay, java.lang.Integer _toYear, java.lang.Integer _toMonth, java.lang.Integer _toDay, java.lang.Integer _utm_e, java.lang.Integer _utm_n, java.lang.Integer _utm_zone, java.lang.Double _latDec, java.lang.Double _lonDec, java.lang.String _latLonFmt) {
        m_name = _name;
        m_stnr = _stnr;
        m_wmoNo = _wmoNo;
        m_amsl = _amsl;
        m_department = _department;
        m_municipalityNo = _municipalityNo;
        m_fromYear = _fromYear;
        m_fromMonth = _fromMonth;
        m_fromDay = _fromDay;
        m_toYear = _toYear;
        m_toMonth = _toMonth;
        m_toDay = _toDay;
        m_utm_e = _utm_e;
        m_utm_n = _utm_n;
        m_utm_zone = _utm_zone;
        m_latDec = _latDec;
        m_lonDec = _lonDec;
        m_latLonFmt = _latLonFmt;

    }

    public java.lang.String getName() {
        return m_name;

    }

    public void setName(java.lang.String _name) {
        m_name = _name;

    }

    public java.lang.Integer getStnr() {
        return m_stnr;

    }

    public void setStnr(java.lang.Integer _stnr) {
        m_stnr = _stnr;

    }

    public java.lang.Integer getWmoNo() {
        return m_wmoNo;

    }

    public void setWmoNo(java.lang.Integer _wmoNo) {
        m_wmoNo = _wmoNo;

    }

    public java.lang.Integer getAmsl() {
        return m_amsl;

    }

    public void setAmsl(java.lang.Integer _amsl) {
        m_amsl = _amsl;

    }

    public java.lang.String getDepartment() {
        return m_department;

    }

    public void setDepartment(java.lang.String _department) {
        m_department = _department;

    }

    public java.lang.Integer getMunicipalityNo() {
        return m_municipalityNo;

    }

    public void setMunicipalityNo(java.lang.Integer _municipalityNo) {
        m_municipalityNo = _municipalityNo;

    }

    public java.lang.Integer getFromYear() {
        return m_fromYear;

    }

    public void setFromYear(java.lang.Integer _fromYear) {
        m_fromYear = _fromYear;

    }

    public java.lang.Integer getFromMonth() {
        return m_fromMonth;

    }

    public void setFromMonth(java.lang.Integer _fromMonth) {
        m_fromMonth = _fromMonth;

    }

    public java.lang.Integer getFromDay() {
        return m_fromDay;

    }

    public void setFromDay(java.lang.Integer _fromDay) {
        m_fromDay = _fromDay;

    }

    public java.lang.Integer getToYear() {
        return m_toYear;

    }

    public void setToYear(java.lang.Integer _toYear) {
        m_toYear = _toYear;

    }

    public java.lang.Integer getToMonth() {
        return m_toMonth;

    }

    public void setToMonth(java.lang.Integer _toMonth) {
        m_toMonth = _toMonth;

    }

    public java.lang.Integer getToDay() {
        return m_toDay;

    }

    public void setToDay(java.lang.Integer _toDay) {
        m_toDay = _toDay;

    }

    public java.lang.Integer getUtm_e() {
        return m_utm_e;

    }

    public void setUtm_e(java.lang.Integer _utm_e) {
        m_utm_e = _utm_e;

    }

    public java.lang.Integer getUtm_n() {
        return m_utm_n;

    }

    public void setUtm_n(java.lang.Integer _utm_n) {
        m_utm_n = _utm_n;

    }

    public java.lang.Integer getUtm_zone() {
        return m_utm_zone;

    }

    public void setUtm_zone(java.lang.Integer _utm_zone) {
        m_utm_zone = _utm_zone;

    }

    public java.lang.Double getLatDec() {
        return m_latDec;

    }

    public void setLatDec(java.lang.Double _latDec) {
        m_latDec = _latDec;

    }

    public java.lang.Double getLonDec() {
        return m_lonDec;

    }

    public void setLonDec(java.lang.Double _lonDec) {
        m_lonDec = _lonDec;

    }

    public java.lang.String getLatLonFmt() {
        return m_latLonFmt;

    }

    public void setLatLonFmt(java.lang.String _latLonFmt) {
        m_latLonFmt = _latLonFmt;

    }


    private java.lang.String m_name;
    private java.lang.Integer m_stnr;
    private java.lang.Integer m_wmoNo;
    private java.lang.Integer m_amsl;
    private java.lang.String m_department;
    private java.lang.Integer m_municipalityNo;
    private java.lang.Integer m_fromYear;
    private java.lang.Integer m_fromMonth;
    private java.lang.Integer m_fromDay;
    private java.lang.Integer m_toYear;
    private java.lang.Integer m_toMonth;
    private java.lang.Integer m_toDay;
    private java.lang.Integer m_utm_e;
    private java.lang.Integer m_utm_n;
    private java.lang.Integer m_utm_zone;
    private java.lang.Double m_latDec;
    private java.lang.Double m_lonDec;
    private java.lang.String m_latLonFmt;

}
