package no.met.metdata.proxy;


/**
 * Java Bean: no_met_metdata_PrecipitationTypes
 *    for Web service proxy: MetDataServiceProxy
 *    generated by Oracle WSDL toolkit (Version: 1.0).
 */
public class no_met_metdata_PrecipitationTypes {

    public no_met_metdata_PrecipitationTypes() {

    }

    public no_met_metdata_PrecipitationTypes(java.lang.String _language, java.lang.String _precipitationCode, java.lang.Integer _precipitationID, java.lang.String _precipitationDescription) {
        m_language = _language;
        m_precipitationCode = _precipitationCode;
        m_precipitationID = _precipitationID;
        m_precipitationDescription = _precipitationDescription;

    }

    public java.lang.String getLanguage() {
        return m_language;

    }

    public void setLanguage(java.lang.String _language) {
        m_language = _language;

    }

    public java.lang.String getPrecipitationCode() {
        return m_precipitationCode;

    }

    public void setPrecipitationCode(java.lang.String _precipitationCode) {
        m_precipitationCode = _precipitationCode;

    }

    public java.lang.Integer getPrecipitationID() {
        return m_precipitationID;

    }

    public void setPrecipitationID(java.lang.Integer _precipitationID) {
        m_precipitationID = _precipitationID;

    }

    public java.lang.String getPrecipitationDescription() {
        return m_precipitationDescription;

    }

    public void setPrecipitationDescription(java.lang.String _precipitationDescription) {
        m_precipitationDescription = _precipitationDescription;

    }


    private java.lang.String m_language;
    private java.lang.String m_precipitationCode;
    private java.lang.Integer m_precipitationID;
    private java.lang.String m_precipitationDescription;

}
