package no.met.metdata.proxy;


/**
 * Java Bean: no_met_metdata_Metdata
 *    for Web service proxy: MetDataServiceProxy
 *    generated by Oracle WSDL toolkit (Version: 1.0).
 */
public class no_met_metdata_Metdata {

    public no_met_metdata_Metdata() {

    }

    public no_met_metdata_Metdata(java.util.Date _created, java.lang.String _type, no.met.metdata.proxy.no_met_metdata_TimeStamp[] _timeStamp) {
        m_created = _created;
        m_type = _type;
        m_timeStamp = _timeStamp;

    }

    public java.util.Date getCreated() {
        return m_created;

    }

    public void setCreated(java.util.Date _created) {
        m_created = _created;

    }

    public java.lang.String getType() {
        return m_type;

    }

    public void setType(java.lang.String _type) {
        m_type = _type;

    }

    public no.met.metdata.proxy.no_met_metdata_TimeStamp[] getTimeStamp() {
        return m_timeStamp;

    }

    public void setTimeStamp(no.met.metdata.proxy.no_met_metdata_TimeStamp[] _timeStamp) {
        m_timeStamp = _timeStamp;

    }


    private java.util.Date m_created;
    private java.lang.String m_type;
    private no.met.metdata.proxy.no_met_metdata_TimeStamp[] m_timeStamp;

}
