package no.met.metdata.proxy;


/**
 * Java Bean: no_met_metdata_FlagProperties
 *    for Web service proxy: MetDataServiceProxy
 *    generated by Oracle WSDL toolkit (Version: 1.0).
 */
public class no_met_metdata_FlagProperties {

    public no_met_metdata_FlagProperties() {

    }

    public no_met_metdata_FlagProperties(java.lang.String _language, java.lang.String _flagName, java.lang.Integer _flagID, java.lang.String _flagDescription, java.lang.String _flagCode) {
        m_language = _language;
        m_flagName = _flagName;
        m_flagID = _flagID;
        m_flagDescription = _flagDescription;
        m_flagCode = _flagCode;

    }

    public java.lang.String getLanguage() {
        return m_language;

    }

    public void setLanguage(java.lang.String _language) {
        m_language = _language;

    }

    public java.lang.String getFlagName() {
        return m_flagName;

    }

    public void setFlagName(java.lang.String _flagName) {
        m_flagName = _flagName;

    }

    public java.lang.Integer getFlagID() {
        return m_flagID;

    }

    public void setFlagID(java.lang.Integer _flagID) {
        m_flagID = _flagID;

    }

    public java.lang.String getFlagDescription() {
        return m_flagDescription;

    }

    public void setFlagDescription(java.lang.String _flagDescription) {
        m_flagDescription = _flagDescription;

    }

    public java.lang.String getFlagCode() {
        return m_flagCode;

    }

    public void setFlagCode(java.lang.String _flagCode) {
        m_flagCode = _flagCode;

    }


    private java.lang.String m_language;
    private java.lang.String m_flagName;
    private java.lang.Integer m_flagID;
    private java.lang.String m_flagDescription;
    private java.lang.String m_flagCode;

}
