package no.met.metdata.proxy;


/**
 * Java Bean: no_met_metdata_TimeStamp
 *    for Web service proxy: MetDataServiceProxy
 *    generated by Oracle WSDL toolkit (Version: 1.0).
 */
public class no_met_metdata_TimeStamp {

    public no_met_metdata_TimeStamp() {

    }

    public no_met_metdata_TimeStamp(java.util.Date _from, no.met.metdata.proxy.no_met_metdata_Location[] _location, java.util.Date _to) {
        m_from = _from;
        m_location = _location;
        m_to = _to;

    }

    public java.util.Date getFrom() {
        return m_from;

    }

    public void setFrom(java.util.Date _from) {
        m_from = _from;

    }

    public no.met.metdata.proxy.no_met_metdata_Location[] getLocation() {
        return m_location;

    }

    public void setLocation(no.met.metdata.proxy.no_met_metdata_Location[] _location) {
        m_location = _location;

    }

    public java.util.Date getTo() {
        return m_to;

    }

    public void setTo(java.util.Date _to) {
        m_to = _to;

    }


    private java.util.Date m_from;
    private no.met.metdata.proxy.no_met_metdata_Location[] m_location;
    private java.util.Date m_to;

}
